/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Almacenamiento.BLPersona;
import Clases.Contagio;
import Clases.Persona;

import java.awt.Desktop;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snaker
 */
public class JFpersona extends javax.swing.JFrame {

    Almacenamiento.BLPersona ManejaPer;
    /**
     * Creates new form JFpersona
     */
//    Map map = new Map();
    JFcontagio contg = new JFcontagio();

    public JFpersona() throws SQLException, ClassNotFoundException {
        this.ManejaPer = new BLPersona();

        initComponents();

        pane1.setVisible(true);
        paneinfo.setVisible(false);

        callmenu();

        Numvalidator(txtcel);
        Numvalidator(txtcedu);
        Numvalidator(txtedad);

        bttactualizar.setVisible(false);
        btteliminar.setVisible(false);
        btteditar.setVisible(false);
        bttcancelar.setVisible(false);

        try {

            RecuperaDatos();

        } catch (IOException | ClassNotFoundException | SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }

    /**
     * This method is c alled from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bttmap = new javax.swing.JButton();
        bttcontagio = new javax.swing.JButton();
        bttmap1 = new javax.swing.JButton();
        bttinfo = new javax.swing.JLabel();
        pane1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bttbuscar = new javax.swing.JButton();
        bttcancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bttguardar = new javax.swing.JButton();
        btteditar = new javax.swing.JButton();
        lblnew = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        bttnuevo = new javax.swing.JButton();
        btteliminar = new javax.swing.JButton();
        bttactualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablap = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sexocmbx = new javax.swing.JComboBox<>();
        txtedad = new javax.swing.JTextField();
        txtdirecc = new javax.swing.JTextField();
        txtcel = new javax.swing.JTextField();
        txtcedu = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        paneinfo = new javax.swing.JPanel();
        labinfoo = new javax.swing.JLabel();
        bttsalir = new javax.swing.JLabel();
        github = new javax.swing.JLabel();

        jLabel4.setText("Mapa de Contagios");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Practicum 2");
        setBackground(new java.awt.Color(102, 255, 0));
        setLocation(new java.awt.Point(500, 500));
        setLocationByPlatform(true);
        setModalExclusionType(null);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttmap.setBackground(new java.awt.Color(102, 0, 0));
        bttmap.setFont(new java.awt.Font("Myanmar Text", 0, 10)); // NOI18N
        bttmap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_google_maps_old_25px.png"))); // NOI18N
        bttmap.setText("Mapa(Localizacion)");
        bttmap.setBorderPainted(false);
        bttmap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttmapActionPerformed(evt);
            }
        });
        jPanel1.add(bttmap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 30));

        bttcontagio.setBackground(new java.awt.Color(102, 0, 0));
        bttcontagio.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        bttcontagio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_coronavirus_25px.png"))); // NOI18N
        bttcontagio.setText("Contagio-\nFechas");
        bttcontagio.setBorderPainted(false);
        bttcontagio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcontagioActionPerformed(evt);
            }
        });
        jPanel1.add(bttcontagio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 30));

        bttmap1.setBackground(new java.awt.Color(102, 0, 0));
        bttmap1.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        bttmap1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_exit_25px.png"))); // NOI18N
        bttmap1.setText("Salir");
        bttmap1.setBorderPainted(false);
        bttmap1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttmap1MouseClicked(evt);
            }
        });
        bttmap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttmap1ActionPerformed(evt);
            }
        });
        jPanel1.add(bttmap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 120, 30));

        bttinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_about_20px.png"))); // NOI18N
        bttinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttinfoMouseClicked(evt);
            }
        });
        jPanel1.add(bttinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 420));

        pane1.setBackground(new java.awt.Color(102, 0, 51));
        pane1.setForeground(new java.awt.Color(255, 0, 102));
        pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 255, 204));
        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Personas");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel1.setOpaque(true);
        pane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 30));

        bttbuscar.setBackground(new java.awt.Color(0, 153, 153));
        bttbuscar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        bttbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-b-icon.png"))); // NOI18N
        bttbuscar.setText("Buscar");
        bttbuscar.setToolTipText("");
        bttbuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null
            , java.awt.Color.darkGray, null, null));
    bttbuscar.setBorderPainted(false);
    bttbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            bttbuscarMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            bttbuscarMouseExited(evt);
        }
    });
    bttbuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bttbuscarActionPerformed(evt);
        }
    });
    pane1.add(bttbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 90, 20));

    bttcancelar.setText("Limpiar_Cancelar");
    bttcancelar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bttcancelarActionPerformed(evt);
        }
    });
    pane1.add(bttcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

    jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(240, 240, 240));
    jLabel8.setText("N° Cedula");
    pane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 60, 20));

    bttguardar.setBackground(new java.awt.Color(0, 153, 153));
    bttguardar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
    bttguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save-as-icon.png"))); // NOI18N
    bttguardar.setText("Guardar");
    bttguardar.setToolTipText("");
    bttguardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null
        , java.awt.Color.darkGray, null, null));
bttguardar.setBorderPainted(false);
bttguardar.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        bttguardarMouseEntered(evt);
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        bttguardarMouseExited(evt);
    }
    });
    bttguardar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bttguardarActionPerformed(evt);
        }
    });
    pane1.add(bttguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 90, 30));

    btteditar.setBackground(new java.awt.Color(0, 153, 153));
    btteditar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
    btteditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-delete-icon.png"))); // NOI18N
    btteditar.setText("Editar/Eliminar");
    btteditar.setToolTipText("");
    btteditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null
        , java.awt.Color.darkGray, null, null));
btteditar.setBorderPainted(false);
btteditar.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        btteditarMouseEntered(evt);
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        btteditarMouseExited(evt);
    }
    });
    btteditar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btteditarActionPerformed(evt);
        }
    });
    pane1.add(btteditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, 20));
    pane1.add(lblnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 90, 20));

    txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            txtbuscarKeyPressed(evt);
        }
    });
    pane1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 170, 30));

    bttnuevo.setBackground(new java.awt.Color(0, 153, 153));
    bttnuevo.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
    bttnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nuevo.png"))); // NOI18N
    bttnuevo.setText("Nuevo Registro");
    bttnuevo.setToolTipText("");
    bttnuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null
        , java.awt.Color.darkGray, null, null));
bttnuevo.setBorderPainted(false);
bttnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        bttnuevoMouseEntered(evt);
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        bttnuevoMouseExited(evt);
    }
    });
    bttnuevo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bttnuevoActionPerformed(evt);
        }
    });
    pane1.add(bttnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, 20));

    btteliminar.setText("Eliminar");
    btteliminar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btteliminarActionPerformed(evt);
        }
    });
    pane1.add(btteliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

    bttactualizar.setText("Actualizar");
    bttactualizar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bttactualizarActionPerformed(evt);
        }
    });
    pane1.add(bttactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

    tablap.setAutoCreateRowSorter(true);
    tablap.setBackground(java.awt.SystemColor.control);
    tablap.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    tablap.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "null"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    tablap.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
    tablap.setCellEditor(null);
    tablap.setDoubleBuffered(true);
    tablap.setGridColor(new java.awt.Color(0, 204, 204));
    tablap.setName("Personas"); // NOI18N
    tablap.setOpaque(false);
    tablap.setSelectionBackground(new java.awt.Color(137, 17, 9));
    tablap.setShowGrid(false);
    tablap.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tablapMouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(tablap);
    if (tablap.getColumnModel().getColumnCount() > 0) {
        tablap.getColumnModel().getColumn(0).setPreferredWidth(5);
        tablap.getColumnModel().getColumn(2).setPreferredWidth(30);
    }

    pane1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 650, 190));

    jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
    jLabel9.setText("Nombres ");
    pane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

    jLabel10.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
    jLabel10.setText("N.Cedula");
    pane1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

    jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
    jLabel11.setText("Telefono");
    pane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

    jLabel12.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
    jLabel12.setText("Dirección");
    pane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

    jLabel13.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
    jLabel13.setText("Edad ");
    pane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

    jLabel14.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
    jLabel14.setText("Sexo");
    pane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

    sexocmbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "M", "F" }));
    sexocmbx.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            sexocmbxActionPerformed(evt);
        }
    });
    pane1.add(sexocmbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));
    pane1.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 40, -1));
    pane1.add(txtdirecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 310, -1));
    pane1.add(txtcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 170, -1));
    pane1.add(txtcedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 130, -1));

    txtnom.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtnomActionPerformed(evt);
        }
    });
    txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            txtnomKeyPressed(evt);
        }
    });
    pane1.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 180, -1));

    jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngtree-covid19-effect-people-wearing-mask-coronavirus-png-image_5336895.jpg"))); // NOI18N
    pane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 400));

    getContentPane().add(pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 990, 400));

    paneinfo.setBackground(new java.awt.Color(51, 255, 255));
    paneinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    labinfoo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    labinfoo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    labinfoo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    paneinfo.add(labinfoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 190));

    bttsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_delete_25px.png"))); // NOI18N
    bttsalir.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            bttsalirMouseClicked(evt);
        }
    });
    paneinfo.add(bttsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 30, 40));

    github.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    github.setToolTipText("");
    github.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    github.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            githubMouseClicked(evt);
        }
    });
    paneinfo.add(github, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 620, 100));

    getContentPane().add(paneinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 790, 310));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sexocmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexocmbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexocmbxActionPerformed

    private void tablapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablapMouseClicked
        // TODO add your handling code here:

        int row = (int) tablap.getSelectedRow();
        int column = (int) tablap.getSelectedColumn();
        //Obtiene el valor de la seleccion
        String strValor = (String) tablap.getModel().getValueAt(row, column);
        //Muestra en la eqiqueta

        //String Id = (String) tablap.getModel().getValueAt(row, 0);
        String cedu = (String) tablap.getModel().getValueAt(row, 0);
        txtcedu.setText(cedu);
        String Nombre = (String) tablap.getModel().getValueAt(row, 1);
        txtnom.setText(Nombre);
        String telefono = (String) tablap.getModel().getValueAt(row, 2);
        txtcel.setText(telefono);
        String direcc = (String) tablap.getModel().getValueAt(row, 3);
        txtdirecc.setText(direcc);
        String edad = (String) tablap.getModel().getValueAt(row, 4);
        txtedad.setText(edad);
        String sexo = (String) tablap.getModel().getValueAt(row, 5);
        sexocmbx.setSelectedItem(sexo);
        bttguardar.setVisible(false);
        boolean bo = true;
        bloqueartxts(bo);
        bttactualizar.setVisible(false);
        btteliminar.setVisible(false);
        btteditar.setVisible(true);

    }//GEN-LAST:event_tablapMouseClicked

    private void btteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btteliminarActionPerformed
        // TODO add your handling code here:

        int op = JOptionPane.showConfirmDialog(null, "Seguro que deseas eliminar?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (op == JOptionPane.YES_OPTION) {

            try {
                Eliminar();
                Limpiar();
                RecuperaDatos();
            } catch (IOException | ClassNotFoundException | SQLException ex) {
                System.out.println(ex.getMessage());
            }

        } else if (op == JOptionPane.YES_NO_CANCEL_OPTION) {
            btteliminar.enableInputMethods(false);

        }


    }//GEN-LAST:event_btteliminarActionPerformed

    private void bttactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttactualizarActionPerformed
        if (txtnom.getText().equals("") || txtcedu.getText().equals("")
                || txtcel.getText().equals("") || txtdirecc.getText().equals("")
                || txtedad.getText().equals("") || sexocmbx.getSelectedItem().equals("Seleccione")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No as ingresado todos los datos");
        } else {
            try {
                Actualizar();
                JOptionPane.showMessageDialog(rootPane, "Datos Actualizado corentamente  ;)");
                Limpiar();
                RecuperaDatos();

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_bttactualizarActionPerformed

    private void bttnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnuevoActionPerformed
        // TODO add your handling code here:
        txtcedu.setEnabled(true);
        txtnom.setEnabled(true);
        txtcel.setEnabled(true);
        txtdirecc.setEnabled(true);
        txtedad.setEnabled(true);
        sexocmbx.setEnabled(true);
        Limpiar();
        bttguardar.setVisible(true);
        //btteditar.setAction();
        btteditar.setVisible(false);
        btteliminar.setVisible(false);

    }//GEN-LAST:event_bttnuevoActionPerformed

    private void txtnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            txtnom.setEditable(true);

            //  (c == KeyEvent.VK_DELETE))) 
        } else {
            //JOptionPane.showMessageDialog(null, "Solo Texto! :)","Nota",JOptionPane.WARNING_MESSAGE);
            txtnom.setEditable(false);
        }
    }//GEN-LAST:event_txtnomKeyPressed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void bttnuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnuevoMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_bttnuevoMouseEntered

    private void bttnuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnuevoMouseExited
        // TODO add your handling code here:
        // this.lblnew.setText(null);
    }//GEN-LAST:event_bttnuevoMouseExited

    private void btteditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btteditarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btteditarMouseEntered

    private void btteditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btteditarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btteditarMouseExited

    private void btteditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btteditarActionPerformed
        // TODO add your handling code here:
        txtcedu.setEnabled(true);
        txtnom.setEnabled(true);
        txtcel.setEnabled(true);
        txtdirecc.setEnabled(true);
        txtedad.setEnabled(true);
        sexocmbx.setEnabled(true);
        bttcancelar.setVisible(true);
        bttactualizar.setVisible(true);
        btteliminar.setVisible(true);


    }//GEN-LAST:event_btteditarActionPerformed

    private void bttguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttguardarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bttguardarMouseEntered

    private void bttguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttguardarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bttguardarMouseExited

    private void bttguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttguardarActionPerformed

        if (txtnom.getText().equals("") || txtcedu.getText().equals("")
                || txtcel.getText().equals("") || txtdirecc.getText().equals("")
                || txtedad.getText().equals("") || sexocmbx.getSelectedItem().equals("Seleccione")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No as ingresado todos los datos");
        } else {

            try {

                if (Guardar() == false) {
                    JOptionPane.showMessageDialog(rootPane, "El id ya esta regitrado ");
                } else {

                    JOptionPane.showMessageDialog(rootPane, "Datos Actualizado corentamente ");
                    Limpiar();
                    RecuperaDatos();
                }

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }

    }//GEN-LAST:event_bttguardarActionPerformed

    private void bttbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttbuscarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bttbuscarMouseEntered

    private void bttbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttbuscarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bttbuscarMouseExited

    private void bttbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttbuscarActionPerformed
        // TODO add your handling code here:

        try {
            Buscar();

            RecuperaDatos();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        btteditar.setVisible(true);
    }//GEN-LAST:event_bttbuscarActionPerformed

    private void bttcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcancelarActionPerformed
        // TODO add your handling code here:
        Limpiar();
        this.btteliminar.setVisible(false);
        this.bttactualizar.setVisible(false);
    }//GEN-LAST:event_bttcancelarActionPerformed

    private void bttcontagioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcontagioActionPerformed
        // TODO add your handling code here:
        ///JFcontagio contg = new JFcontagio();
        contg.setVisible(true);
    }//GEN-LAST:event_bttcontagioActionPerformed

    private void bttmapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttmapActionPerformed

        String linkmap = "https://mapcovi.rf.gd/";

        Desktop enlace = Desktop.getDesktop();

        try {
            enlace.browse(new URI(linkmap));
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo abrir el enlace" + "Revisa tu navegador o conexion "
                    + JOptionPane.ERROR);
            e.getMessage();
        }

    }//GEN-LAST:event_bttmapActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void bttmap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttmap1ActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "Salir?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (op == JOptionPane.YES_OPTION) {

            System.exit(0);

        } else if (op == JOptionPane.YES_NO_CANCEL_OPTION) {

        }

    }//GEN-LAST:event_bttmap1ActionPerformed

    private void bttmap1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttmap1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_bttmap1MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here: 


    }//GEN-LAST:event_jPanel1MouseClicked

    private void bttsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttsalirMouseClicked
        // TODO add your handling code here:
        this.pane1.setVisible(true);
        this.paneinfo.setVisible(false);
    }//GEN-LAST:event_bttsalirMouseClicked

    private void bttinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttinfoMouseClicked
        // TODO add your handling code here:
        this.pane1.setVisible(false);
        this.paneinfo.setVisible(true);

        labinfoo.setText("<html><h2>Sofware par Registro Persona contagiadas de Covid-19 </h2>"
                + "<p> UTPL  **Proyecto Practicum 2** <br>--Wilson Carrion-- 5°Ciclo Informatica-- <br>"
                + "--Oct 2020 --Feb 2021</p>"
                + "<p><h3>Proyecto</h3>"
                + "Pequeño software que permite regitrar, localizar y representar personas\n"
                + "contagiadas de COVID19.<br>"
                + "</p>"
                + "</html>");
        github.setText("<html><p>  <a href= https://github.com/snaker-9/Pryectopracticum2/tree/main>Github</a>  </p>    </html>");


    }//GEN-LAST:event_bttinfoMouseClicked

    private void githubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_githubMouseClicked
        // TODO add your handling code here:
        String link = "https://github.com/snaker-9/Pryectopracticum2/tree/main";

        Desktop enlace = Desktop.getDesktop();

        try {
            enlace.browse(new URI(link));
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(rootPane, "No se pudo abrir el enlace" + "Revisa tu navegaor o conexion "
                    + JOptionPane.ERROR);
            e.getMessage();
        }

    }//GEN-LAST:event_githubMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFpersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFpersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFpersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFpersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFpersona().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFpersona.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JFpersona.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttactualizar;
    private javax.swing.JButton bttbuscar;
    private javax.swing.JButton bttcancelar;
    private javax.swing.JButton bttcontagio;
    private javax.swing.JButton btteditar;
    private javax.swing.JButton btteliminar;
    private javax.swing.JButton bttguardar;
    private javax.swing.JLabel bttinfo;
    private javax.swing.JButton bttmap;
    private javax.swing.JButton bttmap1;
    private javax.swing.JButton bttnuevo;
    private javax.swing.JLabel bttsalir;
    private javax.swing.JLabel github;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labinfoo;
    private javax.swing.JLabel lblnew;
    private javax.swing.JPanel pane1;
    private javax.swing.JPanel paneinfo;
    private javax.swing.JComboBox<String> sexocmbx;
    private javax.swing.JTable tablap;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcedu;
    private javax.swing.JTextField txtcel;
    private javax.swing.JTextField txtdirecc;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables

    public void RecuperaDatos() throws ClassNotFoundException, IOException, SQLException {
        //ArrayList<Institucion> lstInst = objArcInstitucion.RecuperaObjetosInstLST();

        ArrayList<Persona> lstper = ManejaPer.BuscarTodos();

        /*Es necesario crear un objeto con las columnas que se mostrarán en la tabla*/
        Object columnas[] = {"Cedula", "Nombres", "Telefono", "Direccion", "Edad", "Sexo"};
        /*Es necesario añadir las columnas al modelo de la Tabla*/
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        /*Añadidas las columnas y el modelo se setea en la Tabla*/
        tablap.setModel(modelo);
        for (Persona per : lstper) {
            //String id = String.valueOf(per.getIdPersona());
            String cedu = String.valueOf(per.getDNI());
            String nombres = per.getNombres();
            String telefono = per.getTelefono();
            String direccion = per.getDireccion();
            String edad = String.valueOf(per.getEdad());
            String sexo = String.valueOf(per.getSexo());
            //Por cada registro se lo añade a una estructra tipo Arreglo para incluirlo en la Tabla
            String modeloTemp[] = {cedu, nombres, telefono, direccion, edad, sexo};

            //Se añade la estructura al modelo de la Tabla
            modelo.addRow(modeloTemp);
        };

        this.pack();
    }

    public boolean Actualizar() throws SQLException {

        Persona per = new Persona(Integer.parseInt(txtcedu.getText()), txtnom.getText(),
                txtcel.getText(), txtdirecc.getText(), Integer.parseInt(txtedad.getText()),
                String.valueOf(sexocmbx.getSelectedItem()));

        boolean retorno = ManejaPer.Modificar(per);
        return retorno;
    }

    //Método que permite Eliminar un registro usando como parámetro de búsqueda el código
    public void Eliminar() throws SQLException {
        boolean blnresultado = ManejaPer.Eliminar(txtcedu.getText());
        if (blnresultado == true) {
            JOptionPane.showMessageDialog(rootPane, "Registro eliminado con exito");

        } else {
            JOptionPane.showMessageDialog(rootPane, "No se encontró registro a eliminar");
        }
    }

    public void Limpiar() {
        this.txtcedu.setText(null);
        this.txtnom.setText(null);
        this.txtdirecc.setText(null);
        this.txtcel.setText(null);
        this.txtedad.setText(null);
        //this.txtcel.setText(null);
        sexocmbx.setSelectedIndex(0);
    }

    public boolean Guardar() throws SQLException {
        System.out.println("Enviar a Insertar");

        Persona per = new Persona(Integer.parseInt(txtcedu.getText()), txtnom.getText(),
                txtcel.getText(), txtdirecc.getText(), Integer.parseInt(txtedad.getText()), (String) sexocmbx.getSelectedItem());
        boolean retorno = ManejaPer.Registrar(per);
        String s = "";

        return retorno;

    }

    public void Buscar() throws SQLException {
        ArrayList<Persona> lstper = ManejaPer.Buscar2(txtbuscar.getText());
        if (lstper.size() > 0) {
            for (Persona per : lstper) {
                //txtID.setText(String.valueOf(ins.getId()));
                txtcedu.setText(String.valueOf(per.getDNI()));
                txtnom.setText(per.getNombres());
                txtcel.setText(per.getTelefono());
                txtdirecc.setText(per.getDireccion());
                txtedad.setText(String.valueOf(per.getEdad()));
                sexocmbx.setSelectedItem(per.getSexo());

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Registro no encontrado");
            Limpiar();
        }
    }

    public void cargartabla() {
        Object columnas[] = {"Id", "Cedula", "Nombres", "Telefono", "Direccion", "Edad", "Sexo"};
        /*Es necesario añadir las columnas al modelo de la Tabla*/
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        /*Añadidas las columnas y el modelo se setea en la Tabla*/
        tablap.setModel(modelo);

    }

    public void dataok() {

    }

    public boolean bloqueartxts(boolean bo) {

        if (bo = true) {
            txtcedu.setEnabled(false);

            txtnom.setEnabled(false);
            txtcel.setEnabled(false);
            txtdirecc.setEnabled(false);
            txtedad.setEnabled(false);
            sexocmbx.setEnabled(false);
        }
        return false;
    }

    public void f(JTextField txt) {
        if (txt.getText().equals("")) {
            btteliminar.setVisible(false);
        } else {
            btteliminar.setVisible(true);

        }

    }

    public void Numvalidator(JTextField txtField) {
        txtField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!(Character.isDigit(c)
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                    JOptionPane.showMessageDialog(null, "Solo Numeros! :)", "Nota", JOptionPane.WARNING_MESSAGE);
                }
            }
        });
    }

    public void callmenu() {

        contg.Txtmenu(txtcedu);
        contg.Txtmenu(txtnom);
        contg.Txtmenu(txtcel);
        contg.Txtmenu(txtdirecc);
        contg.Txtmenu(txtedad);

    }

    public void noduplic(boolean b) throws SQLException {
        ArrayList<Persona> ls = ManejaPer.BuscarTodos();

        //txtidp.setText(idp);
        ls.forEach((inst) -> {
            // int id = inst.getIdPersona();
            // String id = String.valueOf(inst.getIntPersona());
            int cedu = Integer.valueOf(inst.getDNI());
            String nombres = inst.getNombres();
            String cel = inst.getTelefono();
            String direccion = inst.getDireccion();
            int edad = inst.getEdad();
            String sexo = String.valueOf(inst.getSexo());
            Persona pe = new Persona(cedu, nombres, cel, direccion,
                    edad, sexo);
            // list_model.addPersona(pe);
            // labpersona.setText(id+"\n"+cedu+"\n"+nombres+"     "+tipo);
            //Se añade los elementos al modelo de la lista

            if (txtcedu.getText().equals(cedu)) {
                JOptionPane.showMessageDialog(null, "El Id Ya esta regitrado");
            }
        });
    }
}
